default: &default
  adapter: postgresql
  encoding: SQL_ASCII
  pool: 5
  username: ubuntu
  password: mak99mak99

development:
  <<: *default
  database: mxsh_development

test:
  <<: *default
  database: mxsh_test

production:
  <<: *default
  encoding: unicode
  database: mxsh